name: lumen
volumes:
    lumen_data:

services:
    lumina:
        build: .
        image: ghcr.io/naim94a/lumen:master
        ports:
            - 1234:1234
            - 8082:8082
        environment:
            PKCSPASSWD: $PKCSPASSWD
        volumes:
            - ./dockershare:/dockershare
            - lumen_data:/data
